# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deploy_dlg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from pycaret.datasets import get_data
from pycaret.classification import *
import os
import sys
from subprocess import Popen, PIPE
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import matplotlib
from PIL import Image


class TableModel(QtCore.QAbstractTableModel):

    def __init__(self, data):
        super(TableModel, self).__init__()
        self._data = data

    def data(self, index, role):
        if role == Qt.DisplayRole:
            value = self._data.iloc[index.row(), index.column()]
            return str(value)

    def rowCount(self, index):
        return self._data.shape[0]

    def columnCount(self, index):
        return self._data.shape[1]

    def headerData(self, section, orientation, role):
        # section is the index of the column/row.
        if role == Qt.DisplayRole:
            if orientation == Qt.Horizontal:
                return str(self._data.columns[section])

            if orientation == Qt.Vertical:
                return str(self._data.index[section])


class Ui_deploy_dlg(object):
    def setupUi(self, deploy_dlg):
        deploy_dlg.setObjectName("deploy_dlg")
        deploy_dlg.resize(940, 563)
        self.buttonBox = QtWidgets.QDialogButtonBox(deploy_dlg)
        self.buttonBox.setGeometry(QtCore.QRect(590, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(deploy_dlg)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.data = QtWidgets.QWidget()
        self.data.setObjectName("data")
        self.data_predictions = QtWidgets.QPushButton(self.data)
        self.data_predictions.setGeometry(QtCore.QRect(510, 420, 331, 41))
        self.data_predictions.setObjectName("data_predictions")
        self.data_table = QtWidgets.QTableView(self.data)
        self.data_table.setGeometry(QtCore.QRect(50, 20, 791, 381))
        self.data_table.setObjectName("data_table")
       
        self.data_entry = QtWidgets.QLineEdit(self.data)
        self.data_entry.setGeometry(QtCore.QRect(50, 420, 451, 41))
        self.data_entry.setText("")
        self.data_entry.setReadOnly(False)
        self.data_entry.setObjectName("data_entry")
        self.tabWidget.addTab(self.data, "")
        self.load = QtWidgets.QWidget()
        self.load.setObjectName("load")
        self.save_model_btn = QtWidgets.QPushButton(self.load)
        self.save_model_btn.setGeometry(QtCore.QRect(50, 420, 791, 41))
        self.save_model_btn.setObjectName("save_model_btn")
        self.pred_table = QtWidgets.QTableView(self.load)
        self.pred_table.setGeometry(QtCore.QRect(50, 20, 791, 381))
        self.pred_table.setObjectName("pred_table")
        
        self.tabWidget.addTab(self.load, "")
        self.deploy = QtWidgets.QWidget()
        self.deploy.setObjectName("deploy")
        self.deploy_pred_table = QtWidgets.QTableView(self.deploy)
        self.deploy_pred_table.setGeometry(QtCore.QRect(50, 20, 791, 381))
        self.deploy_pred_table.setObjectName("deploy_pred_table")
      
        self.deploy_btn = QtWidgets.QPushButton(self.deploy)
        self.deploy_btn.setGeometry(QtCore.QRect(50, 420, 791, 41))
        self.deploy_btn.setObjectName("deploy_btn")
        self.tabWidget.addTab(self.deploy, "")

        self.retranslateUi(deploy_dlg)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(deploy_dlg.accept)
        self.buttonBox.rejected.connect(deploy_dlg.reject)
        self.data_predictions.clicked.connect(self.load_data)
        self.save_model_btn.clicked.connect(self.load_class)
        self.deploy_btn.clicked.connect(self.deploy_it)
        
        QtCore.QMetaObject.connectSlotsByName(deploy_dlg)
        

    def retranslateUi(self, deploy_dlg):
        _translate = QtCore.QCoreApplication.translate
        deploy_dlg.setWindowTitle(_translate("deploy_dlg", "Deploy"))
        self.data_predictions.setText(_translate("deploy_dlg", "Load Data"))
        self.data_entry.setPlaceholderText(_translate("deploy_dlg", "Enter target class..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data), _translate("deploy_dlg", "Data"))
        self.save_model_btn.setText(_translate("deploy_dlg", "Load Classifier"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.load), _translate("deploy_dlg", "Load"))
        self.deploy_btn.setText(_translate("deploy_dlg", "Deploy Classifier"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deploy), _translate("deploy_dlg", "Deploy"))

    def load_data(self):
        self.get_data, _ = QFileDialog.getOpenFileName()
        self.get_data = pd.read_csv(self.get_data)
        self.entry = self.data_entry.text()
        self.setup_data = setup(self.get_data, target = self.entry, silent=True, html=False)
        
        self.model_get = TableModel(self.get_data)
        self.data_table.setModel(self.model_get)
        self.data_predictions.setText("Loaded!")

    def load_class(self):
        self.loaded_pkl, _ = QFileDialog.getOpenFileName()
 
        self.loaded_pkl = self.loaded_pkl[:-4]
        self.loaded_model = load_model(self.loaded_pkl)
        
        self.data_model = pull(self.loaded_model)
        self.save_model_btn.setText("Loaded!")
        
        self.model_load = TableModel(self.get_data)
        self.pred_table.setModel(self.model_load)
        self.data_predictions.setText("Loaded!")
        
        
    def deploy_it(self):
        self.save_name, _ = QFileDialog.getSaveFileName()
        self.pred_mod = predict_model(self.loaded_model)
        self.pred_mod.to_csv(path_or_buf= self.save_name)
        self.dataa = pd.read_csv(self.save_name)
        
        

        self.model_save = TableModel(self.dataa)
        self.deploy_pred_table.setModel(self.model_save)        
        
        self.deploy_btn.setText("Deployed and saved!")
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deploy_dlg = QtWidgets.QDialog()
    ui = Ui_deploy_dlg()
    ui.setupUi(deploy_dlg)
    deploy_dlg.show()
    sys.exit(app.exec_())
