# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_dlg(object):
    def setupUi(self, new_dlg):
        new_dlg.setObjectName("new_dlg")
        new_dlg.resize(427, 384)
        self.widget = QtWidgets.QWidget(new_dlg)
        self.widget.setGeometry(QtCore.QRect(40, 28, 341, 318))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        
        self.retranslateUi(new_dlg)
        self.buttonBox.accepted.connect(new_dlg.accept)
        self.buttonBox.rejected.connect(new_dlg.reject)
        QtCore.QMetaObject.connectSlotsByName(new_dlg)
        self.buttonBox.accepted.connect(self.create_report)
    def retranslateUi(self, new_dlg):
        _translate = QtCore.QCoreApplication.translate
        new_dlg.setWindowTitle(_translate("new_dlg", "New Project"))
        self.label.setText(_translate("new_dlg", "Project ID"))
        self.label_3.setText(_translate("new_dlg", "Date/time"))
        self.label_2.setText(_translate("new_dlg", "Notes"))
    def create_report(self):
        session_id = self.lineEdit.text()
        note_id = self.textEdit.toPlainText()
        date = self.dateTimeEdit.date()
        dt_string = date.toString(self.dateTimeEdit.displayFormat())

        file = open(session_id + '_report.txt', 'w')
        file.write(session_id)
        notefile = open(session_id + '_report_notes.txt', 'w')
        notefile.write("Date/time" + dt_string + ", Notes:" + note_id)
        file.close()
        notefile.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_dlg = QtWidgets.QDialog()
    ui = Ui_new_dlg()
    ui.setupUi(new_dlg)
    new_dlg.show()
    sys.exit(app.exec_())
